// Auto-generated. Do not edit!

// (in-package demo01_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AddintsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.progerss_bar = null;
    }
    else {
      if (initObj.hasOwnProperty('progerss_bar')) {
        this.progerss_bar = initObj.progerss_bar
      }
      else {
        this.progerss_bar = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AddintsFeedback
    // Serialize message field [progerss_bar]
    bufferOffset = _serializer.float64(obj.progerss_bar, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AddintsFeedback
    let len;
    let data = new AddintsFeedback(null);
    // Deserialize message field [progerss_bar]
    data.progerss_bar = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'demo01_action/AddintsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '02110171e2018aaea07999b32009b866';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # 3.连续反馈变量
    float64 progerss_bar
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AddintsFeedback(null);
    if (msg.progerss_bar !== undefined) {
      resolved.progerss_bar = msg.progerss_bar;
    }
    else {
      resolved.progerss_bar = 0.0
    }

    return resolved;
    }
};

module.exports = AddintsFeedback;
